name: Output information about issues
on: issue_comment
jobs:
  info-isssue:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue information
        run: echo "${{toJSON(github.event.repository.issues_url)}}"
