name: Output information about issues
on: [issue_comment, issues]
jobs:
  info-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue information
        run: echo "${{toJSON(github.event.repository.issues_url)}}"
